package CoreJavaTraining_Day1;

public class Exception_Handling {

	public static void main(String[] args) {
		
		// This is the line of code causing erro which must be inside the try block	
		// try can have one or multiple catches for different exceptions
		
		try { 
			int output = 1/0;
			System.out.println(output);
			}
			
			catch(ArithmeticException exVar1){   // This is the catch block that contains the erro
				
				}
			
		 /*catch(ArithmeticException2 exVar2){   // This is the catch2 block that contains the erro2
		    	 
			   }
	
             catch(ArithmeticException3 exVar3){   // This is the catch3 block that contains the erro3
                	
                	
                }*/
	 	   }
		
	}


